---
title: "OpenStreetMap"
author: "Miguel Perez Luna"
date: "2/17/2022"
output: html_document
---
```{r}
library(sf)
library(tigris)
library(tidyverse)
library(osmdata)
library(here)
library(tidytransit)
library(r5r)
```

# Downloading the OpenStreetMap Network for the Denver MSA

```{r}
# Load the MSA boundaries
boundary <- core_based_statistical_areas() %>%
  filter(GEOID == "19740")

# Define a bounding box containing the MSA
denver_bbox <- st_bbox(boundary)

q <- opq(bbox = denver_bbox) %>% # create a query
  add_osm_feature(key = 'highway') %>% # request only road data
  osmdata_xml(file = here("existing/networks/streets.osm")) # download osm file
```

# Convert the OSM file to a PBF file

We did this using Homebrew, in the Mac Terminal, and with Arnav's help.

# Downloading GTFS Data

We used tidytransit and view(feedlist) to find the url for the Denver GTFS data.

# Installing 

# Creating Zone centroids (PUT ON HOLD)

```{r}
msaboundaries <- st_read(here("zones",
          "cb_2018_us_cbsa_500k",
          "cb_2018_us_cbsa_500k.shp"))

CO_tractboundaries <- st_read(here("zones",
              "cb_2018_08_tract_500k",
              "cb_2018_08_tract_500k.shp"))
```

```{r}
msa_tracts <- CO_tractboundaries %>%
  filter(COUNTYFP == c("031",
                       "005", 
                       "059",
                       "001",
                       "035",
                       "047",
                       "019",
                       "039",
                       "093",
                       "014"))
  
```

```{r}
centroids <- here("zones",
              "cb_2018_08_tract_500k",
              "cb_2018_08_tract_500k.shp") %>%
  
  st_read() %>%
  st_centroid() %>%
  st_transform("WGS84") %>%
  rename(id = GEOID)
```

